import { useEffect, useState } from 'react'
import { request } from '../../lib/crm'
import { useAuth } from '../../state/AuthContext'
import AdminPageHeader from '../../components/AdminPageHeader'
import '../../security.css'
export default function Security(){
  const {mfa,refresh,logout}=useAuth()
  const [sessions,setSessions]=useState(null),[enrollment,setEnrollment]=useState(null),[password,setPassword]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const load=()=>request('security').then(setSessions)
  useEffect(()=>{let alive=true;request('security').then(v=>{if(alive)setSessions(v)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[])
  const action=async task=>{setBusy(true);setError('');setNotice('');try{await task()}catch(e){setError(e.message)}finally{setBusy(false);setCode('');setPassword('')}}
  const enroll=e=>{e.preventDefault();void action(async()=>{setEnrollment(await request('mfa',{operation:'enroll',password}))})}
  const verify=e=>{e.preventDefault();void action(async()=>{await request('mfa',{operation:'verify',factor_id:enrollment.id,code});setEnrollment(null);await refresh();await load();setNotice('MFA подключена. Следующий вход потребует код.')})}
  const remove=e=>{e.preventDefault();if(!window.confirm('Отключить двухэтапный вход для вашего аккаунта?'))return;void action(async()=>{await request('mfa',{operation:'unenroll',factor_id:mfa.factors[0].id,code});await refresh();await load();setNotice('MFA отключена для вашего аккаунта.')})}
  const revoke=(id)=>{if(!window.confirm(id?'Завершить эту сессию?':'Завершить все остальные сессии?'))return;void action(async()=>{await request('security',{operation:id?'revoke':'revoke_others',id});await load();setNotice('Сессии завершены.')})}
  return <div className="security-page"><AdminPageHeader title="Безопасность аккаунта" text="Двухэтапный вход и ваши активные сессии."/>{error&&<p className="notice notice--error" role="alert">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
    <section className="admin-panel"><h2>Приложение-аутентификатор (TOTP)</h2><p>Подключение добровольное. Пока вы не подтвердите первый код, обычный вход продолжает работать. Сохраните доступ к приложению и резервному устройству в безопасном месте.</p>
      {!mfa?.factors?.length&&!enrollment&&<form className="auth-form" onSubmit={enroll}><label>Текущий пароль<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} className="btn btn--primary">Подключить MFA</button></form>}
      {enrollment&&<form className="auth-form" onSubmit={verify}><p>Отсканируйте QR-код в вашем приложении. Не отправляйте его другим людям. Он отображается только на этом экране.</p><img className="mfa-qr" src={enrollment.qr} alt="QR-код подключения вашего аутентификатора"/><details><summary>Ввести ключ вручную</summary><code className="mfa-secret">{enrollment.secret}</code></details><label>Код из приложения<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy} className="btn btn--primary">Подтвердить подключение</button><button type="button" disabled={busy} className="btn btn--soft" onClick={()=>{setEnrollment(null);setCode('')}}>Отменить</button></form>}
      {!!mfa?.factors?.length&&<><p className="notice">MFA подключена.</p><details><summary>Отключить MFA</summary><form className="auth-form" onSubmit={remove}><label>Свежий код из приложения<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy} className="btn btn--soft">Отключить после проверки</button></form></details></>}
    </section>
    <section className="admin-panel"><h2>Ваши сессии</h2><p>Каждая сессия действует не более 8 часов. Отдельных бессрочных «доверенных устройств» нет: MFA не обходится.</p>{sessions===null?<p role="status">Загрузка…</p>:<ul className="session-list">{sessions.map(s=><li key={s.ref}><div><strong>{s.current?'Текущая сессия':'Другая сессия'}</strong><p>Создана: {new Date(s.created_at).toLocaleString('ru-RU')}<br/>Действует до: {new Date(s.expires_at).toLocaleString('ru-RU')}</p></div>{!s.current&&<button disabled={busy} className="btn btn--soft" onClick={()=>revoke(s.ref)}>Завершить</button>}</li>)}</ul>}<button disabled={busy} className="btn btn--soft" onClick={()=>revoke(null)}>Завершить остальные сессии</button> <button disabled={busy} className="btn btn--soft" onClick={logout}>Выйти на этом устройстве</button></section>
    <section className="admin-panel"><h2>Если доступ потерян</h2><p>Не выходите из доступного устройства, пока не восстановили аутентификатор. Если код получить нельзя, свяжитесь с владельцем. Он проверяет личность и сбрасывает фактор в Supabase Dashboard → Authentication → Users → ваш пользователь → MFA. Для самого владельца нужен доступ к аккаунту Supabase или уполномоченный участник организации. После сброса завершите остальные сессии и подключите MFA заново.</p><p>Эта система не создаёт recovery-коды. Резервирование аутентификатора выполняется средствами выбранного приложения. Пароли, ключи и QR-коды нельзя отправлять в переписке или хранить в CRM.</p></section>
  </div>
}
